seed: 2234
out_path: /lfs01/workdirs/hlwn026u2/keras-kaldi/timit_work//asr_work_timit_deepspeech2
mean_std_file: mean_std_fmllr.npz


model:
    name: deepspeech2
    input_feat: fmllr
    input_dim: 40
    encoders:
     encoder:
      conv_type: conv2d
      conv_kernels: [[11, 41], [11, 21], [11, 11]]
      conv_strides: [[1, 1], [1, 1], [1, 1]]
      conv_filters: [32, 32, 96]
      conv_dropout: 0.1
      rnn_nlayers: 5
      rnn_type: lstm
      rnn_units: 512
      rnn_bidirectional: True
      rnn_rowconv: 0
      rnn_dropout: 0.1
      fc_nlayers: 0
      fc_units: 1024
    outputs:
      output_tri:
        layers:
          - type: dense
            units: 1960
            activation: linear
          - type: batchnormalization
          - type: activation
            name: output_tri
            function: softmax

      output_mono:
        layers:
          - type: dense
            units: 49  # start from 1
            activation: linear
          - type: batchnormalization
          - type: activation
            name: output_mono
            function: softmax

    seq2seq-encoder-decoder1:
      encoder-decoder_1:
        encoder:
          - lstm_units: 500
        decoder:
          - lstm_units: 500
            context_units: 500
            units: 51 # mono + <s> + </s>


loss_weights: {'output_tri' :1.0, 'output_mono': 1.0}                  

optimizer:
    name: adam
    ngpu: 2
    lr: 0.0004 # 1E-4
    batch_size: 4
    beta_1: 0.9
    beta_2: 0.98      
